### ISSUE TITLE
command `rostopic echo /scan_channel` returns nothing

### ISSUE THREAD

**Issue by Tensorfengsheng1926** [tongsky723/lslidar_C16#3]
After executing the command `rostopic echo /scan_channel` in the terminal, the output is empty though it still seems to be keeping running. 
Rviz is able to show the point cloud graph properly.

Also, I ran the Test_MultiChannel.py and no graph to be shown. It seems to be stucked on `msg = rospy.wait_for_message("scan_channel", LslidarC16Layer)` when I interrupted. Numpy and matplotlib are properly installed.
Thanks!

**Comment by tongsky723** [comment]
@Tensorfengsheng1926 
Currently we remove this topic because no user want to use this function, but I forget to strike it out.
As you can check from lslidar_c16_decoder/src/lslidar_c16_decoder.cpp around Line 576, we comment out call to this function. You can uncomment this to publish this data if you want.
``` cpp&line_number=574
if (publish_scan){
    publishScan();
    // publishChannelScan();
}
```
